# Generated by Django 3.1.4 on 2020-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addgoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
