# Generated by Django 3.1.4 on 2020-12-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201212_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgoal',
            name='price',
        ),
    ]
